import type { Language, TranslationMap } from "./types";

export const translations: Record<Language, TranslationMap> = {
  "pt-BR": {
    "header.home":"Home", "header.solutions":"Soluções", "header.about":"Sobre a Global Tech", "header.contact":"Contato", "header.differentials":"Diferenciais", "header.portfolio":"Portfólio", "header.talkToTeam":"Fale com nosso time", "header.openMenu":"Abrir menu", "header.closeMenu":"Fechar menu",
    "language.portuguese":"Português", "language.spanish":"Español", "language.selectPortuguese":"Selecionar português", "language.selectSpanish":"Selecionar espanhol",
    "whatsapp.open":"Abrir atendimento pelo WhatsApp", "whatsapp.close":"Fechar atendimento", "whatsapp.title":"Fale com um consultor", "whatsapp.available":"Atendimento disponível", "whatsapp.nameQuestion":"Olá! Para começar, como você se chama?", "whatsapp.emailQuestion":"Qual é o seu e-mail corporativo?", "whatsapp.phoneQuestion":"Qual é o seu número de telefone?", "whatsapp.employeesQuestion":"Por fim, quantos funcionários sua empresa possui?", "whatsapp.namePlaceholder":"Digite seu nome", "whatsapp.emailPlaceholder":"nome@empresa.com.br", "whatsapp.phonePlaceholder":"(00) 00000-0000", "whatsapp.confirm":"Confirmar", "whatsapp.send":"Enviar", "whatsapp.wait":"Aguarde", "whatsapp.back":"Voltar", "whatsapp.secure":"Seus dados estão seguros conosco.", "whatsapp.typing":"Consultor digitando", "whatsapp.finished":"Perfeito! Recebemos suas informações. Agora vamos direcionar você para um dos nossos consultores.", "whatsapp.reset":"Preencher novamente", "whatsapp.invalidField":"Campo inválido.", "whatsapp.submitError":"Não foi possível enviar seus dados. Tente novamente.", "whatsapp.redirectMessage":"Olá! Meu nome é {name}. Gostaria de saber mais sobre a plataforma de iGaming.", "whatsapp.employee1":"1 a 10", "whatsapp.employee2":"11 a 50", "whatsapp.employee3":"51 a 100", "whatsapp.employee4":"Mais de 100",
    "form.name":"Nome", "form.whatsapp":"WhatsApp", "form.city":"Cidade", "form.submit":"Faça seu cadastro agora!", "form.submitting":"Enviando...", "form.successTitle":"Cadastro enviado!", "form.successMessage":"Obrigado pelo contato. Em breve entraremos em contato com você.", "form.reset":"Preencher novamente", "form.submitError":"Não foi possível enviar agora. Tente novamente em alguns instantes."
  },
  es: {
    "header.home":"Inicio", "header.solutions":"Soluciones", "header.about":"Sobre Global Tech", "header.contact":"Contacto", "header.differentials":"Diferenciales", "header.portfolio":"Portafolio", "header.talkToTeam":"Hable con nuestro equipo", "header.openMenu":"Abrir menú", "header.closeMenu":"Cerrar menú",
    "language.portuguese":"Português", "language.spanish":"Español", "language.selectPortuguese":"Seleccionar portugués", "language.selectSpanish":"Seleccionar español",
    "whatsapp.open":"Abrir atención por WhatsApp", "whatsapp.close":"Cerrar atención", "whatsapp.title":"Hable con un consultor", "whatsapp.available":"Atención disponible", "whatsapp.nameQuestion":"¡Hola! Para empezar, ¿cómo se llama?", "whatsapp.emailQuestion":"¿Cuál es su correo electrónico corporativo?", "whatsapp.phoneQuestion":"¿Cuál es su número de teléfono?", "whatsapp.employeesQuestion":"Por último, ¿cuántos empleados tiene su empresa?", "whatsapp.namePlaceholder":"Ingrese su nombre", "whatsapp.emailPlaceholder":"nombre@empresa.com", "whatsapp.phonePlaceholder":"(00) 00000-0000", "whatsapp.confirm":"Confirmar", "whatsapp.send":"Enviar", "whatsapp.wait":"Espere", "whatsapp.back":"Volver", "whatsapp.secure":"Sus datos están seguros con nosotros.", "whatsapp.typing":"El consultor está escribiendo", "whatsapp.finished":"¡Perfecto! Recibimos su información. Ahora le dirigiremos a uno de nuestros consultores.", "whatsapp.reset":"Completar de nuevo", "whatsapp.invalidField":"Campo inválido.", "whatsapp.submitError":"No fue posible enviar sus datos. Inténtelo nuevamente.", "whatsapp.redirectMessage":"¡Hola! Mi nombre es {name}. Me gustaría saber más sobre la plataforma de iGaming.", "whatsapp.employee1":"1 a 10", "whatsapp.employee2":"11 a 50", "whatsapp.employee3":"51 a 100", "whatsapp.employee4":"Más de 100",
    "form.name":"Nombre", "form.whatsapp":"WhatsApp", "form.city":"Ciudad", "form.submit":"¡Regístrese ahora!", "form.submitting":"Enviando...", "form.successTitle":"¡Registro enviado!", "form.successMessage":"Gracias por contactarnos. Nos comunicaremos con usted pronto.", "form.reset":"Completar de nuevo", "form.submitError":"No fue posible enviar ahora. Inténtelo nuevamente en unos instantes."
  }
};
