import { Fragment } from "react";

import styles from "./politica-de-privacidad.module.css";

type Entry = { type: "heading" | "paragraph"; text: string };

const entries: Entry[] = [
  { type: "heading", text: "Pol\u00edtica de privacidad" },
  { type: "paragraph", text: "GLOBAL TECH INTERNACIONAL S.A.S. tiene como prioridad la protecci\u00f3n de los datos personales, manteniendo todos los aspectos necesarios de seguridad y privacidad. Asimismo, nos comprometemos con la transparencia en el proceso de tratamiento de datos personales de nuestros stakeholders. Por ello, la presente Pol\u00edtica de Privacidad establece c\u00f3mo se realiza la recolecci\u00f3n, uso y transferencia de informaci\u00f3n de clientes u otras personas que acceden o utilizan nuestro sitio web." },
  { type: "paragraph", text: "Al utilizar nuestros servicios, usted entiende que recopilamos y utilizamos su informaci\u00f3n personal conforme a lo descrito en esta Pol\u00edtica, bajo las normas de la Ley de Protecci\u00f3n de Datos Personales (Ley N.\u00ba 18.331), las disposiciones del derecho del consumidor y dem\u00e1s normas aplicables del ordenamiento jur\u00eddico uruguayo." },
  { type: "paragraph", text: "GLOBAL TECH INTERNACIONAL S.A.S., en adelante simplemente GLOBAL TECH, en calidad de Responsable del Tratamiento de Datos, se compromete a lo dispuesto en la presente Pol\u00edtica de Privacidad." },
  { type: "heading", text: "1. \u00bfQu\u00e9 datos recopilamos y con qu\u00e9 finalidad?" },
  { type: "paragraph", text: "Texto sugerido: Quando os visitantes deixam coment\u00e1rios no site, coletamos os dados mostrados no formul\u00e1rio de coment\u00e1rios, al\u00e9m do endere\u00e7o de IP e de dados do navegador do visitante, para auxiliar na detec\u00e7\u00e3o de spam." },
  { type: "paragraph", text: "Uma sequ\u00eancia anonimizada de caracteres criada a partir do seu e-mail (tamb\u00e9m chamada de hash) poder\u00e1 ser enviada para o Gravatar para verificar se voc\u00ea usa o servi\u00e7o. A pol\u00edtica de privacidade do Gravatar est\u00e1 dispon\u00edvel aqui: https://automattic.com/privacy/. Depois da aprova\u00e7\u00e3o do seu coment\u00e1rio, a foto do seu perfil fica vis\u00edvel publicamente junto de seu coment\u00e1rio." },
  { type: "heading", text: "2. Consentimiento" },
  { type: "paragraph", text: "El tratamiento de sus datos personales se realiza con base en su consentimiento. El consentimiento constituye una manifestaci\u00f3n libre, informada e inequ\u00edvoca mediante la cual usted nos autoriza a tratar sus datos. As\u00ed, conforme a lo dispuesto en la Ley de Protecci\u00f3n de Datos Personales, sus datos solo ser\u00e1n recolectados, tratados y almacenados previa y expresamente con su autorizaci\u00f3n." },
  { type: "paragraph", text: "Su consentimiento ser\u00e1 obtenido de manera espec\u00edfica para cada una de las finalidades anteriormente descritas, evidenciando el compromiso de transparencia y buena fe de GLOBAL TECH hacia sus usuarios/clientes, y conforme a las normativas legales vigentes." },
  { type: "paragraph", text: "Al utilizar los servicios de GLOBAL TECH y proporcionar sus datos personales, usted manifiesta estar informado y consentir lo dispuesto en esta Pol\u00edtica de Privacidad, as\u00ed como conocer sus derechos y la forma de ejercerlos." },
  { type: "paragraph", text: "Usted podr\u00e1 revocar su consentimiento en cualquier momento y sin costo alguno." },
  { type: "paragraph", text: "Es importante se\u00f1alar que la revocaci\u00f3n del consentimiento para el tratamiento de sus datos puede afectar el funcionamiento adecuado de algunas funcionalidades del sitio que dependan de dicho tratamiento. Dichas consecuencias ser\u00e1n informadas previamente." },
  { type: "heading", text: "3. \u00bfCu\u00e1les son sus derechos?" },
  { type: "paragraph", text: "GLOBAL TECH garantiza a sus usuarios/clientes el pleno ejercicio de sus derechos como titulares de datos, conforme lo establecido en el art\u00edculo 18 de la Ley de Protecci\u00f3n de Datos Personales. En este sentido, usted puede, en cualquier momento y de forma gratuita:\na. Confirmar la existencia del tratamiento de datos, ya sea de forma simplificada o en un formato claro y completo;\nb. Acceder a sus datos, pudiendo solicitarlos en una copia legible, ya sea en formato impreso o por medios electr\u00f3nicos seguros y adecuados;\nc. Corregir sus datos, mediante la solicitud de edici\u00f3n, rectificaci\u00f3n o actualizaci\u00f3n de los mismos;\nd. Limitar el uso de sus datos cuando estos resulten innecesarios, excesivos o sean tratados en desacuerdo con la normativa vigente, mediante su anonimizaci\u00f3n, bloqueo o eliminaci\u00f3n;\ne. Solicitar la portabilidad de sus datos, a trav\u00e9s de un informe con los datos registrales;\nf. Eliminar sus datos tratados con base en su consentimiento, salvo en los casos legalmente previstos;\ng. Revocar su consentimiento, desautorizando el tratamiento de sus datos;\nh. Informar-se sobre a possibilidade de n\u00e3o fornecer seu consentimento e sobre as consequ\u00eancias da negativa;" },
  { type: "heading", text: "4. \u00bfC\u00f3mo puede ejercer sus derechos como titular?" },
  { type: "paragraph", text: "Para ejercer sus derechos como titular de los datos personales, deber\u00e1 contactarse a trav\u00e9s de los siguientes medios disponibles:\na. E-mail\nCon el fin de garantizar su correcta identificaci\u00f3n como titular de los datos personales objeto de la solicitud, podremos requerir documentos u otras pruebas que acrediten su identidad. En tal caso, usted ser\u00e1 debidamente informado con antelaci\u00f3n." },
  { type: "heading", text: "5. \u00bfC\u00f3mo y por cu\u00e1nto tiempo se almacenar\u00e1n sus datos?" },
  { type: "paragraph", text: "Los datos personales recolectados ser\u00e1n utilizados y almacenados durante el tiempo necesario para la prestaci\u00f3n del servicio o para el cumplimiento de las finalidades descritas en la presente Pol\u00edtica de Privacidad, considerando los derechos tanto del titular de los datos como del responsable del tratamiento.\nEn t\u00e9rminos generales, sus datos ser\u00e1n conservados mientras perdure la relaci\u00f3n contractual entre usted y GLOBAL TECH. Finalizado el per\u00edodo de conservaci\u00f3n de los datos personales, estos ser\u00e1n eliminados de nuestras bases o anonimizados, salvo en los casos legalmente previstos en el art\u00edculo 16 de la Ley de Protecci\u00f3n de Datos Personales, a saber:\na. Cumplimiento de obligaci\u00f3n legal o reglamentaria por parte del responsable del tratamiento;\nb. Estudio por parte de organismos de investigaci\u00f3n, garantizando siempre que sea posible la anonimizaci\u00f3n de los datos personales;\nc. Transferencia a terceros, siempre que se respeten los requisitos legales sobre el tratamiento de datos;\nd. Uso exclusivo del responsable del tratamiento, prohibi\u00e9ndose el acceso por parte de terceros, siempre que los datos est\u00e9n anonimizados." },
  { type: "paragraph", text: "\nEs decir, la informaci\u00f3n personal imprescindible para el cumplimiento de obligaciones legales, judiciales o administrativas, y/o para el ejercicio del derecho de defensa en procedimientos judiciales o administrativos, ser\u00e1 conservada, a\u00fan cuando los dem\u00e1s datos sean eliminados.\nEl almacenamiento de datos recolectados refleja nuestro compromiso con la seguridad y privacidad de su informaci\u00f3n. Aplicamos medidas t\u00e9cnicas y organizativas adecuadas para garantizar la confidencialidad, integridad e inviolabilidad de los datos. Asimismo, contamos con controles de acceso y medidas de seguridad acordes al nivel de riesgo." },
  { type: "heading", text: "6. \u00bfQu\u00e9 hacemos para mantener sus datos seguros?" },
  { type: "paragraph", text: "Para proteger su informaci\u00f3n personal, utilizamos herramientas f\u00edsicas, electr\u00f3nicas y administrativas orientadas a salvaguardar su privacidad.\nAplicamos estas medidas considerando la naturaleza de los datos personales recolectados, el contexto y la finalidad del tratamiento, as\u00ed como los riesgos que eventuales violaciones puedan representar para los derechos y libertades del titular de los datos tratados." },
  { type: "paragraph", text: "Entre las medidas adoptadas, destacamos las siguientes:\na. Solo las personas autorizadas tienen acceso a sus datos personales.\nb. El acceso a sus datos personales se realiza \u00fanicamente despu\u00e9s de asumir un compromiso de confidencialidad.\nc. Sus datos personales se almacenan en un entorno seguro y adecuado." },
  { type: "paragraph", text: "\nGLOBAL TECH se compromete a adoptar las mejores pr\u00e1cticas para evitar incidentes de seguridad. No obstante, es importante destacar que ninguna plataforma digital es completamente segura y libre de riesgos. Es posible que, a pesar de todos nuestros protocolos de seguridad, ocurran incidentes por causas atribuibles exclusivamente a terceros, como ataques cibern\u00e9ticos, o tambi\u00e9n por negligencia o imprudencia del propio usuario/cliente.\nEn caso de incidentes de seguridad que puedan generar riesgo o da\u00f1o relevante para usted o para cualquiera de nuestros usuarios/clientes, se notificar\u00e1 lo ocurrido a los afectados y a la Unidad Reguladora y de Control de Datos Personales (URCDP), conforme a lo dispuesto por la normativa vigente." },
  { type: "heading", text: "7. \u00bfCon qui\u00e9n pueden compartirse sus datos?" },
  { type: "paragraph", text: "GLOBAL TECH, en resguardo de su privacidad, no compartir\u00e1 sus datos personales con ning\u00fan tercero no autorizado.\nSus datos podr\u00e1n ser compartidos con futuros socios comerciales, y en tal caso, se le informar\u00e1 cu\u00e1les datos ser\u00e1n compartidos y con qui\u00e9n.\nDichos terceros recibir\u00e1n sus datos \u00fanicamente en la medida necesaria para la prestaci\u00f3n de los servicios contratados, y nuestros contratos estar\u00e1n alineados con las normas de protecci\u00f3n de datos del ordenamiento jur\u00eddico uruguayo.\nSin embargo, nuestros socios pueden tener sus propias Pol\u00edticas de Privacidad, que pueden diferir de la presente. Recomendamos leer dichos documentos.\nAsimismo, existen otras circunstancias en las que sus datos podr\u00e1n ser compartidos, tales como::\na. Por requerimiento legal, solicitud, orden judicial o administrativa, emitida por autoridades competentes del \u00e1mbito judicial, administrativo o gubernamental;\nb. En el caso de operaciones societarias como fusiones, adquisiciones o incorporaciones, de forma autom\u00e1tica;\nc. Para la protecci\u00f3n de los derechos de GLOBAL TECH en cualquier tipo de conflicto, incluso en el \u00e1mbito judicial.\n" },
  { type: "heading", text: "8. Transferencia internacional de datos" },
  { type: "paragraph", text: "Algunos de los terceros con los que compartimos sus datos pueden estar ubicados o tener instalaciones en pa\u00edses extranjeros. En tales casos, sus datos personales estar\u00e1n igualmente sujetos a la Ley de Protecci\u00f3n de Datos Personales y a las dem\u00e1s normativas aplicables en Uruguay.\nEn este sentido, GLOBAL TECH se compromete a adoptar siempre est\u00e1ndares eficientes de ciberseguridad y protecci\u00f3n de datos, haciendo sus mejores esfuerzos para garantizar el cumplimiento de las exigencias legales correspondientes.\nAl aceptar esta Pol\u00edtica de Privacidad, usted consiente dicha transferencia internacional de datos, la cual se realizar\u00e1 conforme a las finalidades descritas en el presente documento." },
  { type: "heading", text: "9. Cookies o datos de navegaci\u00f3n" },
  { type: "paragraph", text: "GLOBAL TECH utiliza Cookies, que son archivos de texto enviados por la plataforma a su computadora y que se almacenan en ella, conteniendo informaci\u00f3n relacionada con la navegaci\u00f3n en el sitio. En resumen, los Cookies se utilizan para mejorar la experiencia del usuario.\nAl acceder a nuestro sitio web y consentir el uso de Cookies, usted manifiesta conocer y aceptar la utilizaci\u00f3n de un sistema de recolecci\u00f3n de datos de navegaci\u00f3n mediante Cookies en su dispositivo." },
  { type: "paragraph", text: "Usted puede, en cualquier momento y sin costo alguno, modificar las configuraciones, bloquear o rechazar los Cookies. Sin embargo, la revocaci\u00f3n del consentimiento para ciertos Cookies puede impedir el correcto funcionamiento de algunos recursos de la plataforma.\nPara gestionar los Cookies en su navegador, puede hacerlo directamente en la configuraci\u00f3n del mismo, en la secci\u00f3n de administraci\u00f3n de Cookies. Puede acceder a tutoriales sobre el tema en los siguientes enlaces:\na. Si usted utiliza Internet Explorer.\nb. Si usted utiliza Firefox.\nc. Si usted utiliza Safari.\nd. Si usted utiliza Google Chrome.\ne. Si usted utiliza Microsoft Edge.\nf. Si usted utiliza Opera.tuix.com.br" },
  { type: "heading", text: "10. Modificaci\u00f3n de esta Pol\u00edtica de Privacidad" },
  { type: "paragraph", text: "Nos reservamos el derecho de modificar esta Pol\u00edtica de Privacidad en cualquier momento, especialmente en funci\u00f3n de eventuales cambios realizados en nuestro sitio web o por motivos legislativos. Recomendamos que la revise con frecuencia.\nLas modificaciones entrar\u00e1n en vigor a partir de su publicaci\u00f3n en nuestro sitio web, y siempre le notificaremos sobre los cambios realizados. Al utilizar nuestros servicios y proporcionar sus datos personales despu\u00e9s de dichas modificaciones, usted manifiesta su conformidad con ellas." },
  { type: "heading", text: "11. Responsabilidad" },
  { type: "paragraph", text: "GLOBAL TECH reconoce la responsabilidad de los agentes involucrados en los procesos de tratamiento de datos, conforme a lo dispuesto en los art\u00edculos 42 al 45 de la Ley de Protecci\u00f3n de Datos Personales.\nNos comprometemos a mantener esta Pol\u00edtica de Privacidad actualizada, observando sus disposiciones y velando por su cumplimiento.\nAsimismo, asumimos el compromiso de implementar condiciones t\u00e9cnicas y organizativas seguras que sean adecuadas para proteger todo el proceso de tratamiento de datos.\nEn caso de que la Unidad Reguladora y de Control de Datos Personales (URCDP) exija la adopci\u00f3n de medidas relacionadas con el tratamiento de datos realizado por nuestra organizaci\u00f3n, nos comprometemos a cumplirlas." },
  { type: "heading", text: "12. Exenci\u00f3n de responsabilidad" },
  { type: "paragraph", text: "Tal como se menciona en el punto 6, aunque adoptamos altos est\u00e1ndares de seguridad para prevenir incidentes, ninguna p\u00e1gina virtual est\u00e1 completamente libre de riesgos. En tal sentido, GLOBAL TECH no se responsabiliza por:\na. Cualquier consecuencia derivada de la negligencia, imprudencia o impericia de los usuarios en relaci\u00f3n con sus propios datos personales. Garantizamos y nos responsabilizamos \u00fanicamente por la seguridad de los procesos de tratamiento de datos y por el cumplimiento de las finalidades descritas en este documento.\nb. La responsabilidad sobre la confidencialidad de las credenciales de acceso recae exclusivamente en el usuario.\nc. Acciones maliciosas de terceros, como ataques de hackers, salvo que se demuestre conducta dolosa o culposa por parte de GLOBAL TECH;\nd. En caso de incidentes de seguridad que puedan generar riesgo o da\u00f1o relevante para usted o para cualquiera de nuestros usuarios/clientes, se notificar\u00e1 lo sucedido a los afectados y a la Unidad Reguladora y de Control de Datos Personales (URCDP), cumpliendo con las medidas necesarias.\ne. La falsedad de la informaci\u00f3n ingresada por el usuario/cliente en los registros necesarios para la utilizaci\u00f3n de los servicios de GLOBAL TECH;\nf. Cualquier consecuencia derivada de informaciones falsas o proporcionadas de mala fe ser\u00e1 de entera responsabilidad del usuario/cliente." },
  { type: "heading", text: "13. Encargado de Protecci\u00f3n de Datos" },
  { type: "paragraph", text: "Si tiene dudas sobre esta Pol\u00edtica de Privacidad o sobre los datos personales que tratamos, puede ponerse en contacto con nuestro Encargado de Protecci\u00f3n de Datos Personales a trav\u00e9s de los siguientes medios:" },
  { type: "paragraph", text: "Correo electr\u00f3nico: contato@gtech.uy" },
  { type: "paragraph", text: "" },
  { type: "paragraph", text: "Contamos con una lista de pa\u00edses a los que no podemos prestar servicios. Esta incluye Bielorrusia, Cuba, Corea del Norte (RPDC), Ir\u00e1n, Rusia, Siria, Afganist\u00e1n y ciertas regiones sancionadas de Ucrania \u2014 espec\u00edficamente Crimea (Rep\u00fablica Aut\u00f3noma de Crimea y la ciudad de Sebastopol), Donetsk, Lugansk, Jers\u00f3n, Zaporiyia, Dnipr\u00f3 y J\u00e1rkov." },
];

function renderParagraph(text: string) {
  return text.split("\n").map((line, index) => {
    const isListItem = /^[a-h]\./.test(line);
    const content = line.startsWith("Texto sugerido:")
      ? <><strong>Texto sugerido: </strong>{line.slice("Texto sugerido: ".length)}</>
      : isListItem
        ? <><strong>{line.slice(0, 2)}</strong>{line.slice(2)}</>
        : line;

    return <Fragment key={`${line}-${index}`}>{index > 0 ? <br /> : null}{content}</Fragment>;
  });
}

export function PrivacyPolicyContent() {
  return (
    <article className={styles.article}>
      {entries.map((entry, index) => (
        <Fragment key={`${entry.type}-${index}`}>
          {entry.type === "heading" ? <h2>{entry.text}</h2> : <p>{renderParagraph(entry.text)}</p>}
          {entry.text === "9. Cookies o datos de navegaci\u00f3n" ? <ol start={7}><li /></ol> : null}
        </Fragment>
      ))}
    </article>
  );
}
